#!/usr/bin/env python3
"""Build per-frame controller features from extracted raw reference and pose data."""

from __future__ import annotations

import argparse
import json
import pickle
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

try:
    from _bootstrap import PROJECT_ROOT
except ModuleNotFoundError:  # pragma: no cover - used when imported as scripts.*
    from scripts._bootstrap import PROJECT_ROOT

from vehicle_controller.data.feature_builder import build_raw_feature_dataset
from vehicle_controller.features.normalizer import FeatureNormalizer
from vehicle_controller.units import steering_limit_deg_from_config
from vehicle_controller.utils.config import load_yaml


def project_path(path: str | Path) -> Path:
    path = Path(path)
    return path if path.is_absolute() else PROJECT_ROOT / path


def _float_tuple(values: Sequence[str] | None) -> tuple[float, ...] | None:
    if values is None:
        return None
    return tuple(float(value) for value in values)


def config_value(config: Mapping[str, object], section: str, key: str) -> Path:
    section_config = config.get(section)
    if not isinstance(section_config, Mapping) or key not in section_config:
        raise ValueError(f"Missing '{section}.{key}' in the main configuration")
    return project_path(str(section_config[key]))


def build_features_from_raw_data(
    raw_data_path: str | Path,
    output_path: str | Path,
    *,
    config_path: str | Path = "configs/default.yaml",
    model_config_path: str | Path | None = None,
    normalization_config_path: str | Path | None = None,
    normalize_features: bool = True,
    preview_times_s: Sequence[float] = (0.1, 0.2, 0.3, 0.4, 0.5),
    lookahead_distances_m: Sequence[float] | None = None,
    curvature_weights: Sequence[float] = (1.0, 0.8, 0.6, 0.4, 0.2),
) -> Path:
    input_path = project_path(raw_data_path)
    output = project_path(output_path)
    main_config = load_yaml(project_path(config_path))
    resolved_model_config_path = (
        project_path(model_config_path)
        if model_config_path is not None
        else config_value(main_config, "model", "config")
    )
    model_config: dict[str, Any] = dict(load_yaml(resolved_model_config_path))
    normalizer = None
    resolved_normalization_config_path = None
    if normalize_features:
        resolved_normalization_config_path = (
            project_path(normalization_config_path)
            if normalization_config_path is not None
            else config_value(main_config, "data", "normalization")
        )
        normalizer = FeatureNormalizer.from_yaml(str(resolved_normalization_config_path))

    with input_path.open("rb") as file:
        raw_dataset = pickle.load(file)
    entries = raw_dataset.get("entries")
    if not isinstance(entries, Sequence) or isinstance(entries, (str, bytes)):
        raise TypeError(f"Raw data pickle has no entries sequence: {input_path}")

    dataset = build_raw_feature_dataset(
        entries,
        preview_times_s=preview_times_s,
        lookahead_distances_m=lookahead_distances_m,
        curvature_weights=curvature_weights,
        normalizer=normalizer,
        steering_scale_deg=steering_limit_deg_from_config(model_config),
        acceleration_scale_mps2=float(model_config["accel_limit_mps2"]),
    )
    metadata = {
        "source_raw_data_path": str(input_path),
        "source_summary": raw_dataset.get("summary", {}),
        "feature_builder": "vehicle_controller.data.feature_builder",
        "features_are_normalized": bool(normalize_features),
        "normalization_config_path": None
        if resolved_normalization_config_path is None
        else str(resolved_normalization_config_path),
        "model_config_path": str(resolved_model_config_path),
        "target_normalization": {
            "steering_scale_deg": steering_limit_deg_from_config(model_config),
            "accel_scale_mps2": float(model_config["accel_limit_mps2"]),
            "clip": 1.0,
        },
        "preview_times_s": list(preview_times_s),
        "lookahead_distances_m": None
        if lookahead_distances_m is None
        else list(lookahead_distances_m),
        "curvature_weights": list(curvature_weights),
        "entry_count": int(len(entries)),
        "frame_count": int(dataset.raw_features.shape[0]),
    }
    return dataset.save_npz(output, metadata)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--raw-data",
        default="data/interim/clean_ad_policy_sim_v1_aba9e399_raw_data.pkl",
        help="Pickle generated by scripts/extract_task_raw_data.py.",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="data/processed/clean_ad_policy_sim_v1_aba9e399_features.npz",
        help="Output NPZ path.",
    )
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--model-config")
    parser.add_argument("--normalization-config")
    parser.add_argument(
        "--no-feature-normalization",
        action="store_true",
        help="Keep features equal to raw_features instead of applying FeatureNormalizer.",
    )
    parser.add_argument(
        "--preview-times-s",
        nargs=5,
        default=("0.1", "0.2", "0.3", "0.4", "0.5"),
        help="Five preview time horizons used when lookahead distances are not fixed.",
    )
    parser.add_argument(
        "--lookahead-distances-m",
        nargs=5,
        help="Optional five fixed lookahead distances. Overrides preview time conversion.",
    )
    parser.add_argument(
        "--curvature-weights",
        nargs=5,
        default=("1.0", "0.8", "0.6", "0.4", "0.2"),
        help="Five weights used to combine sampled trajectory curvature.",
    )
    args = parser.parse_args()

    output = build_features_from_raw_data(
        args.raw_data,
        args.output,
        config_path=args.config,
        model_config_path=args.model_config,
        normalization_config_path=args.normalization_config,
        normalize_features=not args.no_feature_normalization,
        preview_times_s=tuple(float(value) for value in args.preview_times_s),
        lookahead_distances_m=_float_tuple(args.lookahead_distances_m),
        curvature_weights=tuple(float(value) for value in args.curvature_weights),
    )
    data = dict()
    import numpy as np

    with np.load(output, allow_pickle=False) as npz:
        metadata = json.loads(str(npz["metadata_json"]))
        data["features_shape"] = tuple(npz["features"].shape)
        data["raw_features_shape"] = tuple(npz["raw_features"].shape)
        data["targets_shape"] = tuple(npz["targets"].shape)
        data["valid_targets"] = int(npz["target_valid_mask"].sum())
        data["physical_targets_shape"] = tuple(npz["physical_targets"].shape)
        data["frame_count"] = metadata["frame_count"]
        data["features_are_normalized"] = metadata["features_are_normalized"]
    print(f"output={output}")
    print(f"features_shape={data['features_shape']}")
    print(f"raw_features_shape={data['raw_features_shape']}")
    print(f"targets_shape={data['targets_shape']}")
    print(f"physical_targets_shape={data['physical_targets_shape']}")
    print(f"valid_targets={data['valid_targets']}")
    print(f"features_are_normalized={data['features_are_normalized']}")
    print(f"frames={data['frame_count']}")


if __name__ == "__main__":
    main()
