#!/usr/bin/env python3
"""Build raw-data supervised features and run imitation training."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

try:
    from _bootstrap import PROJECT_ROOT
except ModuleNotFoundError:  # pragma: no cover - used when imported as scripts.*
    from scripts._bootstrap import PROJECT_ROOT

try:
    from build_features_from_raw_data import build_features_from_raw_data
    from train_imitation import train_imitation
except ModuleNotFoundError:  # pragma: no cover - used when imported as scripts.*
    from scripts.build_features_from_raw_data import build_features_from_raw_data
    from scripts.train_imitation import train_imitation


def project_path(path: str | Path) -> Path:
    path = Path(path)
    return path if path.is_absolute() else PROJECT_ROOT / path


def _float_tuple(values: Sequence[str] | None) -> tuple[float, ...] | None:
    if values is None:
        return None
    return tuple(float(value) for value in values)


def train_imitation_from_raw_data(
    *,
    raw_data: str | Path,
    dataset_output: str | Path,
    checkpoint_output: str | Path,
    config: str | Path = "configs/default.yaml",
    model_config: str | Path | None = None,
    training_config: str | Path | None = None,
    normalization_config: str | Path | None = None,
    epochs: int | None = None,
    device: str | None = None,
    preview_times_s: Sequence[float] = (0.1, 0.2, 0.3, 0.4, 0.5),
    lookahead_distances_m: Sequence[float] | None = None,
    curvature_weights: Sequence[float] = (1.0, 0.8, 0.6, 0.4, 0.2),
    no_feature_normalization: bool = False,
    no_loss_plot: bool = False,
    loss_curve_output: str | Path = "artifacts/reports/raw_data_imitation/loss_curve.png",
    loss_history_output: str | Path = "artifacts/reports/raw_data_imitation/loss_history.csv",
    comparison_output_dir: str | Path | None = None,
    max_comparison_scenarios: int | None = None,
    max_comparison_samples: int = 2000,
    no_showcase: bool = False,
    showcase_output_dir: str | Path = "artifacts/reports/raw_data_imitation/showcase",
    show_plots: bool = False,
) -> Path:
    dataset_path = build_features_from_raw_data(
        raw_data,
        dataset_output,
        config_path=config,
        model_config_path=model_config,
        normalization_config_path=normalization_config,
        normalize_features=not no_feature_normalization,
        preview_times_s=preview_times_s,
        lookahead_distances_m=lookahead_distances_m,
        curvature_weights=curvature_weights,
    )
    return train_imitation(
        config=config,
        dataset=dataset_path,
        epochs=epochs,
        output=checkpoint_output,
        device=device,
        model_config=model_config,
        training_config=training_config,
        loss_curve_output=loss_curve_output,
        loss_history_output=loss_history_output,
        no_loss_plot=no_loss_plot,
        comparison_output_dir=comparison_output_dir,
        max_comparison_scenarios=max_comparison_scenarios,
        max_comparison_samples=max_comparison_samples,
        showcase_output_dir=showcase_output_dir,
        no_showcase=no_showcase,
        show_plots=show_plots,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--raw-data",
        default="data/interim/clean_ad_policy_sim_v1_aba9e399_raw_data.pkl",
        help="Pickle generated by scripts/extract_task_raw_data.py.",
    )
    parser.add_argument(
        "--dataset-output",
        default="data/processed/clean_ad_policy_sim_v1_aba9e399_imitation_dataset.npz",
        help="Intermediate supervised NPZ dataset used by imitation training.",
    )
    parser.add_argument(
        "--checkpoint-output",
        default="artifacts/checkpoints/raw_data_imitation.pt",
        help="Output checkpoint path.",
    )
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--model-config")
    parser.add_argument("--training-config")
    parser.add_argument("--normalization-config")
    parser.add_argument("--epochs", type=int)
    parser.add_argument("--device", help="Training device. Defaults to cuda when available, else CPU/config.")
    parser.add_argument(
        "--preview-times-s",
        nargs=5,
        default=("0.1", "0.2", "0.3", "0.4", "0.5"),
    )
    parser.add_argument("--lookahead-distances-m", nargs=5)
    parser.add_argument(
        "--curvature-weights",
        nargs=5,
        default=("1.0", "0.8", "0.6", "0.4", "0.2"),
    )
    parser.add_argument("--no-feature-normalization", action="store_true")
    parser.add_argument("--no-loss-plot", action="store_true")
    parser.add_argument(
        "--loss-curve-output",
        default="artifacts/reports/raw_data_imitation/loss_curve.png",
    )
    parser.add_argument(
        "--loss-history-output",
        default="artifacts/reports/raw_data_imitation/loss_history.csv",
    )
    parser.add_argument("--comparison-output-dir")
    parser.add_argument(
        "--max-comparison-scenarios",
        type=int,
        default=0,
        help="Maximum clips/scenarios to plot per split. Use 0 to plot all.",
    )
    parser.add_argument("--max-comparison-samples", type=int, default=2000)
    parser.add_argument("--no-showcase", action="store_true")
    parser.add_argument(
        "--showcase-output-dir",
        default="artifacts/reports/raw_data_imitation/showcase",
    )
    parser.add_argument("--show-plots", action="store_true")
    args = parser.parse_args()

    checkpoint = train_imitation_from_raw_data(
        raw_data=args.raw_data,
        dataset_output=args.dataset_output,
        checkpoint_output=args.checkpoint_output,
        config=args.config,
        model_config=args.model_config,
        training_config=args.training_config,
        normalization_config=args.normalization_config,
        epochs=args.epochs,
        device=args.device,
        preview_times_s=tuple(float(value) for value in args.preview_times_s),
        lookahead_distances_m=_float_tuple(args.lookahead_distances_m),
        curvature_weights=tuple(float(value) for value in args.curvature_weights),
        no_feature_normalization=args.no_feature_normalization,
        no_loss_plot=args.no_loss_plot,
        loss_curve_output=args.loss_curve_output,
        loss_history_output=args.loss_history_output,
        comparison_output_dir=args.comparison_output_dir,
        max_comparison_scenarios=(
            None if args.max_comparison_scenarios <= 0 else args.max_comparison_scenarios
        ),
        max_comparison_samples=args.max_comparison_samples,
        no_showcase=args.no_showcase,
        showcase_output_dir=args.showcase_output_dir,
        show_plots=args.show_plots,
    )
    print(f"raw_data_imitation_checkpoint={checkpoint}")


if __name__ == "__main__":
    main()
